<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.0 (Python 3.8.8 on win32)" generated="20210401 12:24:03.334" rpa="false" schemaversion="2">
<suite id="s1" name="Webinar" source="C:\Users\aldo-\storyboard_workspace\webinar">
<suite id="s1-s1" name="Test" source="C:\Users\aldo-\storyboard_workspace\webinar\test">
<suite id="s1-s1-s1" name="Press Button" source="C:\Users\aldo-\storyboard_workspace\webinar\test\press_button.robot">
<test id="s1-s1-s1-t1" name="Press Button">
<kw name="Press Middle Button" library="lua_writer_PYTHON_wrapper">
<var>${output}</var>
<msg timestamp="20210401 12:24:03.377" level="FAIL">CalledProcessError: Command '['sblua', 'lua_do_stuff_aldo.lua']' returned non-zero exit status 1.</msg>
<status status="FAIL" starttime="20210401 12:24:03.363" endtime="20210401 12:24:03.377"/>
</kw>
<doc>Simply press the middle</doc>
<tag>button</tag>
<status status="FAIL" starttime="20210401 12:24:03.363" endtime="20210401 12:24:03.378">CalledProcessError: Command '['sblua', 'lua_do_stuff_aldo.lua']' returned non-zero exit status 1.</status>
</test>
<status status="FAIL" starttime="20210401 12:24:03.352" endtime="20210401 12:24:03.378"/>
</suite>
<status status="FAIL" starttime="20210401 12:24:03.350" endtime="20210401 12:24:03.379"/>
</suite>
<status status="FAIL" starttime="20210401 12:24:03.335" endtime="20210401 12:24:03.379"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
<stat pass="0" fail="1" skip="0">button</stat>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Webinar">Webinar</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1" name="Test">Webinar.Test</stat>
<stat pass="0" fail="1" skip="0" id="s1-s1-s1" name="Press Button">Webinar.Test.Press Button</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>
